apiVersion: v1
kind: Pod
metadata:
  name: multi-container
  labels:
    Project : roboshop
    purpose: multi-container-demo
spec:
  containers:
  - name: nginx   # multiple Container must have - name
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: [ "sleep", "1000" ]  # Keep the container running
