apiVersion: v1
kind: Pod
metadata:
  name: env-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: pod-secret # Reference to a Secret named 'pod-secret' in 10-secret.yaml


#  kubectl apply -f 11-pod-secret.yaml
# kubectl get pods