apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: service-demo
  ports:
  - protocol: TCP
    port: 80  # service port
    targetPort: 80 # container port



---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  containers:
  - name: nginx
    image: nginx


# kubectl apply -f 12-service.yaml
# kubectl get pods
# kubectl get services
# kubectl describe service nginx or svc nginx
# kubectl get pods -o wide