apiVersion: v1
kind: Service
metadata:
  name: nginx-LB
  labels:
    purpose: service-LB-demo
spec:
  type: LoadBalancer
  selector:
    purpose: service-LB-demo
    project: roboshop
    environment: dev
  ports:
  - protocol: TCP
    port: 80  # service port
    targetPort: 80 # container port



---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-LB
  labels:
    purpose: service-LB-demo
    project: roboshop
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx


# kubectl apply -f 14-service-LB.yaml
# kubectl get pods
# kubectl get services or svc
# kubectl describe service nginx-LB or svc nginx-LB
# kubectl get pods -o wide