apiVersion: v1
kind: Deployment
metadata: 
  name: nginx
  # Deployment labels
  labels:
    purpose: deployment-demo
    project: roboshop
    environment: dev
    app: nginx
spec:
  replicas: 3 # number of pod replicas
# these are the labels for deployment to create pods replicas this should match with pod labels
  selector:
    matchLabels:
      purpose: deployment-demo
      project: roboshop
      environment: dev
      app: nginx
  # This is pod definition
  template:
    metadata:
      labels:
        purpose: deployment-demo
        project: roboshop
        environment: dev
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl # latest stable version with Perl support

# if we delete the one pod, deployment will create a new pod automatically
# kubectl apply -f 16-deployment.yaml
# kubectl get pods
# kubectl get rs
# kubectl describe rs nginx
# kubectl get pods -o wide
# kubectl delete rs nginx